### ISSUE TITLE
latest stable release version? 0.2.9 or 0.2.10?

### ISSUE THREAD

**Issue by ilovezfs** [labstack/tunnel-client#8]
https://github.com/labstack/tunnel/releases/latest points to 0.2.9 but https://github.com/labstack/tunnel/releases shows there is a 0.2.10

**Comment by vishr** [comment]
It was sitting in the draft, just released it.

**Comment by ilovezfs** [comment]
Thanks @vishr! 0.2.10 shipped in Homebrew https://github.com/Homebrew/homebrew-core/pull/28935
